name: NuGet
on:
  push:
    branches:
      - main

jobs:
  nuget:
    name: https://api.nuget.org/v3/index.json
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
      - name: Pack
        run: |
          dotnet pack -c Release --output nupkgs Autobus.Abstractions/Autobus.Abstractions.csproj
          dotnet pack -c Release --output nupkgs Autobus/Autobus.csproj
          dotnet pack -c Release --output nupkgs Autobus.Extensions.Hosting/Autobus.Extensions.Hosting.csproj
          dotnet pack -c Release --output nupkgs Autobus.Serializers.BinaryRecords/Autobus.Serializers.BinaryRecords.csproj
          dotnet pack -c Release --output nupkgs Autobus.Serializers.Json/Autobus.Serializers.Json.csproj
          dotnet pack -c Release --output nupkgs Autobus.Transports.RabbitMQ/Autobus.Transports.RabbitMQ.csproj
          dotnet pack -c Release --output nupkgs Autobus.Loggers.Serilog/Autobus.Loggers.Serilog.csproj
      - name: Publish
        run: |
          dotnet nuget push "nupkgs/Autobus.*.nupkg" -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
